### ISSUE TITLE
User is able to select both monthly and hourly

### ISSUE THREAD

**Issue by siennang** [thraxy/swe-project#2]

**Comment by thraxy** [comment]
# Issue 2

User is able to select both **monthly** and **hourly** options

## Issue is still present
The error I am receiving is:
```
Fatal error: Uncaught mysqli_sql_exception: Table 'parking_facilities_db.parking_facilities' doesn't exist in C:\xampp\htdocs\swe-project-main\swe-project-main\park\search.php:18 Stack trace: #0 C:\xampp\htdocs\swe-project-main\swe-project-main\park\search.php(18): mysqli_query(Object(mysqli), 'SELECT * FROM p...') #1 {main} thrown in C:\xampp\htdocs\swe-project-main\swe-project-main\park\search.php on line 18
```
Since I recently added another radio button for both options for the user, it also runs into the issue where it can be deselected and all the options become selected. It will not choose between the 3 options. 

Also, this error does not relate to the buttons being selected/deselected. It has to do with the search another issue similar to Issue 1. 

## How I am approaching this problem
My approach to this problem will be to change or add to the code so that the user can choose between the 3 buttons but only 1 can be **TRUE** and the others can only be **FALSE**. 

As for the search, I believe I will have to figure out the issue the script is having with the database.

**Comment by thraxy** [comment]
# Issue Resolved

The issue for selecting between the 3 options is now resolved

## Changes
I changed the name="option", previously they all had their own name. 
```
  <form name="form1" method="get" action="search.php">
        <input type="text" placeholder="Search for Parking..." name="search">
        <input type="submit" name="submit" value="Search"> 
        <input type="radio" id="monthly" name="option" value="monthly">
        <label for="monthly">Monthly</label>
        <input type="radio" id="hourly" name="option" value="hourly">
        <label for="hourly">Hourly</label>
        <input type="radio" id="both" name="option" value="both">
        <label for="both">Both</label>
```
